// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5e0bdd09-c967-4224-a26d-1e749875f8a3";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSignalVoltageChange();
void onSignalFrecuencyChange();

CloudElectricPotential signalVoltage;
CloudFrequency signalFrecuency;
CloudTemperatureSensor signalTemperature;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(signalVoltage, READWRITE, 1 * SECONDS, onSignalVoltageChange);
  ArduinoCloud.addProperty(signalFrecuency, READWRITE, ON_CHANGE, onSignalFrecuencyChange);
  ArduinoCloud.addProperty(signalTemperature, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
